### ISSUE TITLE
All messages are spoken regardless of what is selected by the user

### ISSUE THREAD

**Issue by DingusHammer** [phyce/rl-natural-speech#10]
I only have public messages selected, but I still get system and dialog messages spoken even without them selected.
I have attached a screenshot of my settings.
![Screenshot 2024-04-17 133950](https://github.com/phyce/rl-natural-speech/assets/167348109/f32b76db-64b1-4599-9fa1-d7810e5236f0)

**Comment by phyce** [comment]
Thanks for letting us know! I think I know what's causing this. expect a fix soon

**Comment by phyce** [comment]
@DingusHammer I can confirm the dialog messages are still playing even when turned off. I can't replicate any system messages playing when disabled though. Is it some specific system messages that still get played? Please let me know so I can test and see what's going on. I will push the fix now for the dialogues, and if you come back to me with which system messages still get played, I'll look into that further.

**Comment by DingusHammer** [comment]
@phyce The only system messages I get are examine texts (at least I think those are considered game messages). Also, I am still getting dialog messages though I'm not sure if I need to update things on my end to get the update.

**Comment by phyce** [comment]
Ahh yes you're right they do still play. those should be disabled by unticking the `Examine text` option. I have also now fixed that. The update will be automatically downloaded when runelite devs approve the update after reviewing it.

**Comment by LouisGameDev** [comment]
for reference, fixed in: dc436e6407a83dbabc8422ec646715cff792311e  and c3c021cf7e1a707c794385247baae8329dd3a09d in [1.2.1](https://github.com/phyce/rl-natural-speech/releases/tag/1.2.1)
