### ISSUE TITLE
Muting Others mutes yourself too, Muting Yourself does nothing

### ISSUE THREAD

**Issue by techgaud** [phyce/rl-natural-speech#11]
![image](https://github.com/phyce/rl-natural-speech/assets/168145410/6e4de275-e729-41cc-b3eb-41f8e2a3a94c)
Muting Others mutes yourself too, Muting Yourself does nothing

**Comment by LouisGameDev** [comment]
thank you for submitting the issue, we'll look into reproducing this issue.

**Comment by phyce** [comment]
This is now fixed, expect an update soon.

**Comment by LouisGameDev** [comment]
Version 1.2.3 commit [bab62ea]
