### ISSUE TITLE
[Feature Request] Grouping of Male/Female voices

### ISSUE THREAD

**Issue by Tademonn** [phyce/rl-natural-speech#18]
When we want to manually change voice of someone due to the sex mismatch, you have to randomly try out multiple numbers to findout if they're male or female.

It would be nice to have some kind of grouping (for example 1-450 are male, 450-911 are female) to easily switch between the two when it's incorrecly assigned.

**Comment by phyce** [comment]
You can open the voice explorer and search male or female to filter, and you can preview each voice there by pressing on the green play button

![IMG-20241111-WA0023.jpg](https://github.com/user-attachments/assets/a3765c16-47d7-433e-b6fa-eebe73e64d47)

**Comment by Tademonn** [comment]
Thanks a lot for this, I completely missed this section of the plugin, this is more than sufficient.
