### ISSUE TITLE
Filtering voices by gender doesn't seem to work

### ISSUE THREAD

**Issue by wanieru** [phyce/rl-natural-speech#4]
Reproduction steps:
1. Install all the voice packs
2. Open the voice list
3. Click the arrow next to the "Enter name or gender" field
4. Select "Female"

Result: No voices show up at all

Expected result: The female voices should still be visible

**Comment by LouisGameDev** [comment]
Reproducible, thank you. Will fix

**Comment by LouisGameDev** [comment]
fixed! 0b94c18

thank you!


https://github.com/phyce/rl-natural-speech/assets/1916460/ef543c2f-b248-48b7-94cd-7c4537160a6d
