### ISSUE TITLE
Add more non-English voices? :heart: 

### ISSUE THREAD

**Issue by wanieru** [phyce/rl-natural-speech#5]
I think it can be quite charming to have a wide variety of accents, so I'd love to have more non-English voices like the Spanish and German voices that are already available. Granted, some of the piper voices seem to not work quite well with English text - for example, I tried the Chinese model from the piper voices repo, and it was pretty much unintelligible when speaking English. But any other languages where you can understand it despite the accent, would be really nice to have!

**Comment by LouisGameDev** [comment]
glad you were able to try out the other voices on piper voices repository. 

Agreed, will add more next update. (currently, v1.0.1)

**Comment by phyce** [comment]
Yes, more voices are on the way! were are also looking at adding custom voice repositories, and instructions on how to train your own voice. Expect atleast a few more languages in the next update. 
Most languages don't have more than 1 voice, and each voice model loaded adds up 70-150 MB ram.
I've found some datasets that should allow me to train models with many speakers in several other languages.

**Comment by phyce** [comment]
German and Vienamese added. Expect more languages in the near future
