### ISSUE TITLE
Virilis does not update speech with shortened phrases

### ISSUE THREAD

**Issue by BuzzfeedBlue** [phyce/rl-natural-speech#7]
![image](https://github.com/phyce/rl-natural-speech/assets/24302678/e63c6cb8-80b5-4b1f-9410-1ad18537fa8b)

this npc seems to say bannote instead of bank note. I wanted to add an override to make it slow down and pronounce it correctly. When i type in chat, it is said correctly. I wanted to make sure the phrases were working so i made idk=lol and it worked fine. I then tried to make the npc say hello instead of nilsal, which also did not work.

I dont know if this is an issue with npcs overall or just this one being a part of the new area

**Comment by LouisGameDev** [comment]
Hi @BuzzfeedBlue, yes, our text replacement/expansion skips in-game dialogue right now. We can apply this feature to apply to all spoken text. 

I'll discuss with my teammate @phyce. If we agree, then we'll update this in version 1.3 so text expansion applies to all speech.

Thanks for reaching out! Nice UI setup, I like the retro look. Also, version 1.3 will have the Microsoft Sam voice (aka, Gary Gilbert). 


https://github.com/phyce/rl-natural-speech/assets/1916460/919029ff-e621-4b80-9013-0e87cdaacbd6

**Comment by BuzzfeedBlue** [comment]
thanks for the quick response! I wasnt aware of the npc vs player split for the custom phrases. Love that the sam voice will also be available thats so funny.

**Comment by phyce** [comment]
The abbreviation feature was introduced to replace them in user messages, as NPCs don't really use them. We can add a checkbox to enable custom abbreviations for npc dialogs/overhead text to use the common/custom abbreviations.
This would only work with individual words though

**Comment by BuzzfeedBlue** [comment]
It would be appreciated to have the option. Instead of using it for abbreviations I've been using it to "fix" words that's are pronounced oddly

**Comment by phyce** [comment]
Added to 1.3.0
