### ISSUE TITLE
Setting voices for NPCs does not work

### ISSUE THREAD

**Issue by firestrife2** [phyce/rl-natural-speech#8]
Hello! Love this plugin. I have no issues setting different voices for players, but when I configure npc voices (for example when a female has a male voice) - no matter what I do it stays exactly the same. I've tried restarting the entire plugin after changing and it still sticks to the same voice.

**Comment by LouisGameDev** [comment]
Hi Firestrife2, I'm glad you're enjoying Natural Speech. 

1. Which NPC were you trying to set voices for? 
2. Is setting bugged for all NPCs?

I might be able to help you in detail in our discord 
[![Discord](https://discord.com/api/guilds/1214848661029392405/widget.png?style=banner2)](https://discord.gg/Zg5hMYMZ6E)

Also, just excited to share, version 1.3 update is in development, current RuneLite PluginHub version is 1.2. New voices will include the fan favorite voice of Gary Gilbert (Microsoft Sam) from the J1mmy YouTube series!

**Comment by phyce** [comment]
Seems like after jagex updates sometimes retrieving NPC IDs doesn't work properly

**Comment by phyce** [comment]
I believe this is fixed now, expect to get the update soon.
